<?php
/*
@edmaRef: @theme_edma/layout
 */

defined('MOODLE_INTERNAL') || die();

$templatecontext = [
    'sitename'                  => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
    'output'                    => $OUTPUT,
    'pageheading'               => $pageheading,
    'leftblocks'                => $leftblocks,
    'user_profile_picture'      => new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg'),
    'profile_icon_username'     => $edmaProfileIconUsername,
    'login_url'                 => $login_url,
    'signup_url'                => $signup_url,
    'isloggedin'                => $isloggedin,
    'sidepreblocks'             => $blockshtml,
    'hasblocks'                 => $hasblocks,
    'bodyattributes'            => $bodyattributes,
    'primarymoremenu'           => $primarymenu['moremenu'],
    'secondarymoremenu'         => $secondarynavigation ?: false,
    'mobileprimarynav'          => $primarymenu['mobileprimarynav'],
    'usermenu'                  => $primarymenu['user'],
    'langmenu'                  => $primarymenu['lang'],
    'headercontent'             => $headercontent,
    'overflow'                  => $overflow,
    'addblockbutton'            => $addblockbutton,
    'blocks_fullwidth_top'      => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom'   => $blocks_fullwidth_bottom,
    'blocks_above_content'      => $blocks_above_content,
    'has_blocks_above_content'  => !empty($blocks_above_content),
    'blocks_below_content'      => $blocks_below_content,
    'has_blocks_below_content'  => !empty($blocks_below_content),
    'has_blocks_fullwidth_top'  => !empty($blocks_fullwidth_top),
    'regionmainsettingsmenu'    => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'edma_globalsearch_navbar' => $edma_globalsearch_navbar,
    'logo_visibility'           => $logo_visibility,
    'main_logo'                 => $main_logo,
    'logo_styles'               => $logo_styles,
    'mobile_logo'               => $mobile_logo,
    'mobile_logo_styles'        => $mobile_logo_styles,
    'header_search_bar'         => $header_search,
    'top_header_content'        => $top_header_content,
    'top_header_right_content'  => $top_header_right_content,
    'top_header'                => $top_header,
    'header_btn_text'           => $header_btn_text,
    'header_btn_url'            => $header_btn_url,
    'header_left_btn_text'      => $header_left_btn_text,
    'header_left_btn_url'       => $header_left_btn_url,
    'offcanvas_content'         => $offcanvas_content,
    'offcanvas_social_title'    => $offcanvas_social_title,
    'header_btn_icon'           => $header_btn_icon,
    'hide_global_banner'     => $hide_global_banner == 0,

    'footer_logo_visibility'    => $footer_logo_visibility,
    'main_footer_logo'          => $main_footer_logo,
    'footer_logo_styles'        => $footer_logo_styles,
    'hide_guest_access_curriculum'  => $hide_guest_access_curriculum == 0,
    'favicon'                   => $favicon,

    'social_target_href' => $social_target_href,
    'edma_facebook_url' => get_config('theme_edma', 'edma_facebook_url'),
    'edma_twitter_url' => get_config('theme_edma', 'edma_twitter_url'),
    'edma_instagram_url' => get_config('theme_edma', 'edma_instagram_url'),
    'edma_pinterest_url' => get_config('theme_edma', 'edma_pinterest_url'),
    'edma_dribbble_url' => get_config('theme_edma', 'edma_dribbble_url'),
    'edma_google_url' => get_config('theme_edma', 'edma_google_url'),
    'edma_youtube_url' => get_config('theme_edma', 'edma_youtube_url'),
    'edma_vk_url' => get_config('theme_edma', 'edma_vk_url'),
    'edma_500px_url' => get_config('theme_edma', 'edma_500px_url'),
    'edma_behance_url' => get_config('theme_edma', 'edma_behance_url'),
    'edma_digg_url' => get_config('theme_edma', 'edma_digg_url'),
    'edma_flickr_url' => get_config('theme_edma', 'edma_flickr_url'),
    'edma_foursquare_url' => get_config('theme_edma', 'edma_foursquare_url'),
    'edma_linkedin_url' => get_config('theme_edma', 'edma_linkedin_url'),
    'edma_medium_url' => get_config('theme_edma', 'edma_medium_url'),
    'edma_meetup_url' => get_config('theme_edma', 'edma_meetup_url'),
    'edma_snapchat_url' => get_config('theme_edma', 'edma_snapchat_url'),
    'edma_tumblr_url' => get_config('theme_edma', 'edma_tumblr_url'),
    'edma_vimeo_url' => get_config('theme_edma', 'edma_vimeo_url'),
    'edma_wechat_url' => get_config('theme_edma', 'edma_wechat_url'),
    'edma_whatsapp_url' => get_config('theme_edma', 'edma_whatsapp_url'),
    'edma_wordpress_url' => get_config('theme_edma', 'edma_wordpress_url'),
    'edma_weibo_url' => get_config('theme_edma', 'edma_weibo_url'),
    'edma_telegram_url' => get_config('theme_edma', 'edma_telegram_url'),
    'edma_moodle_url' => get_config('theme_edma', 'edma_moodle_url'),
    'edma_amazon_url' => get_config('theme_edma', 'edma_amazon_url'),
    'edma_slideshare_url' => get_config('theme_edma', 'edma_slideshare_url'),
    'edma_soundcloud_url' => get_config('theme_edma', 'edma_soundcloud_url'),
    'edma_leanpub_url' => get_config('theme_edma', 'edma_leanpub_url'),
    'edma_xing_url' => get_config('theme_edma', 'edma_xing_url'),
    'edma_bitcoin_url' => get_config('theme_edma', 'edma_bitcoin_url'),
    'edma_twitch_url' => get_config('theme_edma', 'edma_twitch_url'),
    'edma_github_url' => get_config('theme_edma', 'edma_github_url'),
    'edma_gitlab_url' => get_config('theme_edma', 'edma_gitlab_url'),
    'edma_forumbee_url' => get_config('theme_edma', 'edma_forumbee_url'),
    'edma_trello_url' => get_config('theme_edma', 'edma_trello_url'),
    'edma_weixin_url' => get_config('theme_edma', 'edma_weixin_url'),
    'edma_slack_url' => get_config('theme_edma', 'edma_slack_url'),

    'footer_copyright'      => $footer_copyright,
    'banner_shape_image'    => $banner_shape_image,
    'banner_shape_image2'    => $banner_shape_image2,
    'banner_shape_image3'    => $banner_shape_image3,
    'footer_shape_image1'    => $footer_shape_image1,
    'footer_shape_image2'    => $footer_shape_image2,
    'back_to_top'           => $back_to_top == 0,

    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'footer_col_1_title' => get_config('theme_edma', 'footer_col_1_title'),
    'footer_col_1_body' => format_text(get_config('theme_edma', 'footer_col_1_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_2_title' => get_config('theme_edma', 'footer_col_2_title'),
    'footer_col_2_body' => format_text(get_config('theme_edma', 'footer_col_2_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_3_title' => get_config('theme_edma', 'footer_col_3_title'),
    'footer_col_3_body' => format_text(get_config('theme_edma', 'footer_col_3_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_4_title' => get_config('theme_edma', 'footer_col_4_title'),
    'footer_col_4_body' => format_text(get_config('theme_edma', 'footer_col_4_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_5_title' => get_config('theme_edma', 'footer_col_5_title'),
    'footer_col_5_body' => format_text(get_config('theme_edma', 'footer_col_5_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),

];
$PAGE->requires->jquery();